simulation:
  start_x:      [  -24,   -23,  -22,  -21,  -20, -19]
  start_y:      [    6,     7,    8,    9,   10,  11]
  start_theta:  [  -90,   -75,  -60,  -45,  -30, -15]

  target_x:     [  -10,     2,  15.5,  19,   22,  24]
  target_y:     [-12.5,   -13, -12.5,  -7,   -2,   9]
