simulation:
  start_x:      [  -18,   -19,  -20,  -21,  -22,  -23]
  start_y:      [  -14,   -13,  -12,  -11,  -10,   -9]
  start_theta:  [    0,    15,   30,   45,   60,   75]

  target_x:     [   19,   22,   24,  13.5,    0,  -13]
  target_y:     [   -7,   -2,    9,    13,   13, 11.5]
